name: Build BluebelStudio

on:
  push:
    tags:
      - "v*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qt6-base-dev -y
      - run: make release-linux

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: make release-windows

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: make release-mac

      - uses: actions/upload-artifact@v4
        with:
          name: BluebelStudio-mac
          path: dist/
