name: Build BluebelStudio

on:
  push:

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev pkg-config

      - name: Build
        run: make release-linux


  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        shell: bash
        run: |
          python -m pip install aqtinstall
          aqt install-qt windows desktop 6.8.0 win64_mingw -m qtwidgets

      - name: Setup Qt
        shell: bash
        run: |
          echo "$PWD/Qt/6.8.0/mingw_64/bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=$PWD/Qt/6.8.0/mingw_64/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build
        run: make release-windows


  mac:
    name: macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          brew install qt pkg-config

      - name: Setup Qt
        run: |
          echo "PKG_CONFIG_PATH=$(brew --prefix qt)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build
        run: make release-mac