name: Build BluebelStudio

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev pkg-config

      - name: Build Linux
        run: make release-linux


  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          python -m pip install aqtinstall
          aqt install-qt windows desktop 6.8.0 win64_mingw -m qtwidgets

      - name: Build Windows
        run: make release-windows


  mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          python3 -m pip install aqtinstall
          aqt install-qt mac desktop 6.8.0 clang_64 -m qtwidgets

      - name: Build macOS
        run: make release-mac
